# .goreleaser.yml
version: 2  # Specify the config version
project_name: backhaul
builds:
  - id: backhaul
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -ldflags=-s -w
    env:
      - CGO_ENABLED=0